inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Rails/I18nLocaleTexts:
  Enabled: false